# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#add/buildkite-test-analytics
  # Common artifact paths used across steps
  - &artifact_paths
    - build/test-results/**/*
    - build/reports/**/*

agents:
  queue: "android"

steps:
  - label: "Publish :fluxc-annotations"
    key: "publish-fluxc-annotations"
    command: .buildkite/publish-fluxc-annotations.sh
    plugins: *common_plugins

  - label: "Publish :fluxc-processor"
    key: "publish-fluxc-processor"
    depends_on:
      - "publish-fluxc-annotations"
    command: .buildkite/publish-fluxc-processor.sh
    plugins: *common_plugins

  - label: "Publish :fluxc"
    key: "publish-fluxc"
    depends_on:
      - "publish-fluxc-processor"
      - "publish-fluxc-annotations"
    command: .buildkite/publish-fluxc.sh
    plugins: *common_plugins

  - label: "Publish :plugins:woocommerce"
    key: "publish-plugins-woocommerce"
    depends_on:
      - "publish-fluxc-processor"
      - "publish-fluxc-annotations"
      - "publish-fluxc"
    command: .buildkite/publish-plugins-woocommerce.sh
    plugins: *common_plugins

  - label: "checkstyle"
    command: |
      cp gradle.properties-example gradle.properties && cp -a example/properties-example/ example/properties/
      ./gradlew checkstyle
    artifact_paths: *artifact_paths

  - label: "ktlint"
    command: |
      cp gradle.properties-example gradle.properties && cp -a example/properties-example/ example/properties/
      ./gradlew ktlint
    artifact_paths: *artifact_paths

  - label: "Lint"
    command: |
      cp gradle.properties-example gradle.properties && cp -a example/properties-example/ example/properties/
      ./gradlew lintRelease || (grep -A20 -B2 'severity="Error"' */build/**/*.xml; exit 1);
      find . -iname "*XMLRPCClient*java" | xargs grep getSiteId && (echo "You should not use _getSiteId_ in a XMLRPClient, did you mean _selfHostedId_?" && exit 1) || exit 0;
    artifact_paths: *artifact_paths

  - label: "Unit Test"
    command: .buildkite/unit-tests.sh
    artifact_paths: *artifact_paths
    plugins: *common_plugins

  - label: "WooCommerce Tests"
    command: .buildkite/woocommerce-tests.sh
    artifact_paths: *artifact_paths
    plugins: *common_plugins

  - label: "Connected Tests"
    command: .buildkite/connected-tests.sh
    artifact_paths: *artifact_paths
    plugins: *common_plugins
