# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.3.0

agents:
  queue: "android"

steps:
  - label: "Publish :fluxc-annotations"
    key: "publish-fluxc-annotations"
    command: .buildkite/publish-fluxc-annotations.sh
    plugins: *common_plugins

  - label: "Publish :fluxc-processor"
    key: "publish-fluxc-processor"
    depends_on:
      - "publish-fluxc-annotations"
    command: .buildkite/publish-fluxc-processor.sh
    plugins: *common_plugins

  - label: "Publish :fluxc"
    key: "publish-fluxc"
    depends_on:
      - "publish-fluxc-processor"
      - "publish-fluxc-annotations"
    command: .buildkite/publish-fluxc.sh
    plugins: *common_plugins

  - label: "Publish :plugins:woocommerce"
    key: "publish-plugins-woocommerce"
    depends_on:
      - "publish-fluxc-processor"
      - "publish-fluxc-annotations"
      - "publish-fluxc"
    command: .buildkite/publish-plugins-woocommerce.sh
    plugins: *common_plugins

  - label: "checkstyle"
    command: |
      cp gradle.properties-example gradle.properties && cp -a example/properties-example/ example/properties/
      ./gradlew --stacktrace checkstyle

  - label: "ktlint"
    command: |
      cp gradle.properties-example gradle.properties && cp -a example/properties-example/ example/properties/
      ./gradlew --stacktrace ktlint

  - label: "Lint"
    command: |
      cp gradle.properties-example gradle.properties && cp -a example/properties-example/ example/properties/
      ./gradlew --stacktrace lintRelease || (grep -A20 -B2 'severity="Error"' */build/**/*.xml; exit 1);
      find . -iname "*XMLRPCClient*java" | xargs grep getSiteId && (echo "You should not use _getSiteId_ in a XMLRPClient, did you mean _selfHostedId_?" && exit 1) || exit 0;

  - label: "Unit Test"
    command: |
      cp gradle.properties-example gradle.properties && cp -a example/properties-example/ example/properties/
      ./gradlew --stacktrace example:testRelease plugins:woocommerce:testRelease

  - label: "WooCommerce Tests"
    command: |
      cp gradle.properties-example gradle.properties && cp -a example/properties-example/ example/properties/
      wget $API_TEST_SITE_URL
      ./gradlew --stacktrace :tests:api:test
